name: live-ai-signals

on:
  schedule:
    - cron: "0 */2 * * *"   # her 2 saatte bir
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      # AI eşiklerini istersen burada ayarla
      PTH_BASE: "0.90"
      PTH_META: "0.60"
      PTH_KNN:  "0.58"
      PTH_LSTM: "0.60"
      USE_LSTM: "0"   # 1 yaparsan p_lstm gösterilir (model dosyası gerekir)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        run: |
          python bot_live_ai.py
